### ISSUE TITLE
ecosystem/install

### ISSUE THREAD

**Issue by jarrodmillman** [scientific-python/scientific-python.org#103]
https://github.com/scientific-python/scientific-python.org/blob/main/content/en/ecosystem/install.md

Focus on virtual environments, since this is a best-practice for scientific Python users (as opposed to using system Python + system package managers, for example). There's still the problem of which workflow specifically to highlight. Here I would advocate for two specifically: one based on Python built-ins (i.e. pip and venv) and one based on conda.  It may also make sense to incorporate Juanita's "Spyder says: Don't mix pip and conda"
- https://www.youtube.com/watch?v=Ul79ihg41Rs

- [ ] Remove info on non-recommended installation methods
  - [ ] Remove info on installing w/ system package managers (see #112)
  - [ ] Remove info on binaries (see #112)
  - [ ] Reword section on installing from source to link to the "developer installation" info. (see #112)
- [ ] Maybe grab Hello scipy from next steps.
- [ ] Add section about using virtual environments?
- [ ] Add section about building from source that links to the developer videos.
- [ ] ...
- [ ] Record video

**Comment by rossbar** [comment]
I've add #140, which addresses all the remaining bullets except:
 1. Whether to add a section on virtualenvs, and
 2. recording the video

I think introducing virtual environments is a good idea, but I'm not sure if it will fit in the video. I'll make another PR to try to add as concise a section as possible.

**Comment by jarrodmillman** [comment]
Closed by #188.
